### PR TITLE
Servo and VL53L0X urho backends

### PR DESCRIPTION
**Pull request by RuthgerD**
Backend drivers for various smartcar_lib sensors, servo and the VL53L0X

### CODE REVIEW

**Comment by AeroStun** [comment]
@RuthgerD Please review L3G4200D stuff against the smartcar_shield GY50 impl

**Comment by RuthgerD** [comment]
Looks good, smartcar_shields' GY50 isn't doing anything weird so should work with the backend driver.

**Comment by RuthgerD** [comment]
Note: squashed but still need to credit the correct authors

**Comment by RuthgerD** [comment]
Authors credited, should be mergeable now.

**Comment by RuthgerD** [comment]
weird ci bug :|

**Pull request merged**
