### PR TITLE
Runtime compilation

### LINKED ISSUE #2: Compile compliant cxx files
> As a user I want my C++ code to be compiled by the emulator

### PR DESCRIPTION
**Pull request by RuthgerD**
Fixes #2 #3 #4 

needs squash.

### CODE REVIEW

**Comment by platisd** [comment]
Since you (probably) were pair programming on this task, you should get another member of the team to code review this pull request.

**Comment by platisd** [comment]
> @AeroStun AeroStun requested a review from platisd 31 seconds ago

:laughing: I won't be doing the code review either, especially since it's already merged. :sweat_smile:

**Comment by AeroStun** [comment]
None of the others know C++ or CMake, which quickly gets problematic when it comes to reviewing code in these languages

**Comment by platisd** [comment]
> None of the others know C++ or CMake, which quickly gets problematic when it comes to reviewing code in these languages

About time they start learning or at least start learning to review it then? Having only one (or two? I haven't understood, it was mainly commits by one person) working on a component of the system sounds very risky!

**Comment by AeroStun** [comment]
(There were originally 36 commits done by two people; I simply squashed out the quick-fixes)
IMO pair programming if done right is basically just instantaneous code review to begin with
Of course it would be much better to get at least a third person on board with the review process of that kind of code, but I doubt we will effectively have someone learn enough to get reviewing even in a week of time; not to help, this story is effectively a must for the 4 others to test the code for the story they have chosen to work on.

But sure, we get the idea; more people to review = less chances of huge flaws that need to be fixed later on
Hopefully @davidos-b can leverage his past knowledge of C to help us get a better overview of what can be improved.

**Pull request merged**
